---
# tasks file for iac-ansible-iptables

- name: Check firewalld (RHEL)
  command: yum list installed firewalld
  args:
    warn: false
  register: firewalld_installed
  ignore_errors: true
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
    - firewall_disable_firewalld
  check_mode: false

- name: Disable firewalld service (RHEL)
  service:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - ansible_service_mgr == "service"
    - ansible_os_family == "RedHat"
    - firewall_disable_firewalld
    - firewalld_installed.rc == 0

- name: Disable firewalld service (RHEL)
  systemd:
    name: firewalld.service
    state: stopped
    enabled: false
    force: yes
    ignore_errors: yes
  when:
    - ansible_service_mgr == "systemd"
    - ansible_os_family == "RedHat"
    - firewall_disable_firewalld
    - firewalld_installed.rc == 0

- name: Check if ufw package is installed (on Ubuntu).
  command: service ufw status
  args:
    warn: false
  register: ufw_installed
  ignore_errors: true
  changed_when: false
  when:
    - ansible_distribution == "Ubuntu"
    - firewall_disable_ufw
  check_mode: false

- name: Disable ufw firewall (Ubuntu)
  service:
    name: ufw
    state: stopped
    enabled: false
  when:
    - ansible_service_mgr == "service"
    - ansible_distribution == "Ubuntu"
    - firewall_disable_ufw
    - ufw_installed.rc == 0

- name: Disable ufw firewall (Ubuntu)
  systemd:
    name: ufw.service
    state: stopped
    enabled: false
    force: yes
    ignore_errors: yes
  when:
    - ansible_service_mgr == "systemd"
    - ansible_os_family == "Ubuntu"
    - firewall_disable_ufw
    - ufw_installed.rc == 0
...