---
# tasks file for iac-ansible-iptables

- name: "Define parametros do sysctl.conf"
  sysctl:
    name: "{{ item.name }}"
    state: present
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.accept_source_route', value: '0'  }
    - { name: 'net.ipv4.conf.all.log_martians', value: '1' }
    - { name: 'net.ipv4.conf.all.rp_filter', value: '1' }
    - { name: 'net.ipv4.conf.all.secure_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.accept_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.secure_redirects', value: '0' }
    - { name: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
    - { name: 'net.ipv4.icmp_ignore_bogus_error_messages', value: '1' }
    - { name: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1' }
    - { name: 'net.ipv4.tcp_syncookies', value: '1' }
    - { name: 'net.ipv6.conf.all.accept_ra', value: '0' }
    - { name: 'net.ipv6.conf.all.disable_ipv6', value: '0' }
  register: SYSCTL

- name: "Define o arquivo de regras /etc/rules"
  copy: 
    src: etc-rules 
    dest: /etc/rules 
    owner: root 
    group: root 
    mode: 0444
  register: RULES
  when: ( SYSCTL is sucess )

- name: "Define o arquivo inicalizacao de servico (Firewall) /etc/init.d/firewall"
  copy: 
    src: etc-initd-firewall 
    dest: /etc/init.d/firewall 
    owner: root 
    group: root 
    mode: 0555
  when: ( RULES is sucess )
  notify: 
    - Restart iptables
...
